#!/bin/sh

# xinitrc is typically used to start window managers or desktop environments.
# Similarly to xprofile, it allows the user to excute commands at the
# beginning of the x user session - before the wm or de is started.
# Display managers generally source xprofile, as opposed to xinitrc.
# startx script is a front-end to xinit, and will run commands from xinitrc.

# When connected, output to HDMI-1 as well.
xrandr --output HDMI-1 --mode 1920x1080 --rate 60 &

# X rate <delay> <rate>
xset r rate 290 50 &

# Prevents laptop screen from dimming
xset -dpms &

# Disable the laptop's trackpad
xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 0 &

# Poof the cursor when idle for 2 second
unclutter --timeout 15 --jitter 10 &

# Make ALT_R a compose key
setxkbmap -option compose:ralt &

#  Lightweight compositor for X11
picom --experimental-backends &

# Start pulseaudio as a service
# daemonize must be set to yes in daemon.conf because pulse does not have a service for runit.
pulseaudio --start &

# Input Method Framework
fcitx5 -d &

# screenshot
flameshot &

# file syncthing
syncthing -no-browser &

# redshift
redshift -c ~/.config/redshift/redshift.conf &

# Statusbar loop
while true; do
      xsetroot -name "$(date +"%x %A %X %Z")"
	sleep 1s	# update status every X seconds
done &

# Allow dwm to be initialized by startx. startx cannot be called here.
# Remember that new lines below an exec command are ignored, and thus must be called last.
exec dwm
