require("iris.options")
require("iris.keymaps")
require("iris.autocmds")
require("iris.plugins")
require("iris.colorscheme")
require("iris.lsp")
-- source plugin configurations
require("iris.conf.autopairs")
require("iris.conf.comment")
require("iris.conf.telescope")
require("iris.conf.cmp")
require("iris.conf.gitsigns")
require("iris.conf.nvim-tree")
require("iris.conf.treesitter")
require("iris.conf.lualine")
require("iris.conf.toggleterm")
